### ISSUE TITLE
Heal command cause server crash

### ISSUE THREAD

**Issue by SuperAlecs** [yescallop/EssentialsNK#17]
This is crash log
2017-2-7 16:40:40 [EMERGENCY] Exception happened while ticking server
2017-2-7 16:40:40 [ALERT] java.lang.NoSuchMethodError: cn.nukkit.Player.getHealth()I
	at cn.yescallop.essentialsnk.command.defaults.HealCommand.execute(HealCommand.java:41)
	at cn.nukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:225)
	at cn.nukkit.Server.dispatchCommand(Server.java:644)
	at cn.nukkit.Player.handleDataPacket(Player.java:2941)
	at cn.nukkit.network.Network.processPackets(Network.java:185)
	at cn.nukkit.network.Network.processBatch(Network.java:156)
	at cn.nukkit.Player.handleDataPacket(Player.java:1902)
	at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:155)
	at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:123)
	at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:66)
	at cn.nukkit.network.Network.processInterfaces(Network.java:76)
	at cn.nukkit.Server.tick(Server.java:997)
	at cn.nukkit.Server.tickProcessor(Server.java:800)
	at cn.nukkit.Server.start(Server.java:779)
	at cn.nukkit.Server.<init>(Server.java:464)
	at cn.nukkit.Nukkit.main(Nukkit.java:68)

**Comment by Snake1999** [comment]
Sorry, I can not locate the problem without:
1. Platform and device configurations;
2. Nukkit build date or build identifier;
3. Detailed instruction to reproduce this problem. For example, 'I tried to use `/heal lmlstarqaq` but failed'.

That's all :/

**Comment by yescallop** [comment]
Reproduced. This causes by Nukkit API update, just recompile it to fix this issue.

**Comment by SuperAlecs** [comment]
thx for fix @yescallop

**Comment by ghost** [comment]
Sorry to comment on a closed issue but do I just need to recompile the plugin as I couldn't see a commit for the fix?

**Comment by yescallop** [comment]
@Apqu I'm sure about that, and I've released a new version 1.0.8. You can just update it to fix.
