### ISSUE TITLE
/fly Hard Crash the server

### ISSUE THREAD

**Issue by Nathan31973** [yescallop/EssentialsNK#22]
hello today i just install essentials and when i was testing commands out the /fly command Hard Crash the server every time.
error code
[EMERGENCY] Exception happened while ticking server
23:53:30 [ALERT] java.lang.NoSuchMethodError: cn.nukkit.AdventureSettings.canFly()Z
        at cn.yescallop.essentialsnk.EssentialsAPI.canFly(EssentialsAPI.java:99)
        at cn.yescallop.essentialsnk.EssentialsAPI.switchCanFly(EssentialsAPI.java:93)
        at cn.yescallop.essentialsnk.command.defaults.FlyCommand.execute(FlyCommand.java:40)
        at cn.nukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:245)
        at cn.nukkit.Server.dispatchCommand(Server.java:643)
        at cn.nukkit.Player.handleDataPacket(Player.java:2546)
        at java.util.ArrayList.forEach(Unknown Source)
        at cn.nukkit.network.Network.processPackets(Network.java:169)
        at cn.nukkit.network.Network.processBatch(Network.java:151)
        at cn.nukkit.Player.handleDataPacket(Player.java:1985)
        at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:157)
        at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:132)
        at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:66)
        at cn.nukkit.network.Network.processInterfaces(Network.java:75)
        at cn.nukkit.Server.tick(Server.java:990)
        at cn.nukkit.Server.tickProcessor(Server.java:799)
        at cn.nukkit.Server.start(Server.java:778)
        at cn.nukkit.Server.<init>(Server.java:469)
        at cn.nukkit.Nukkit.main(Nukkit.java:68)

23:53:30 [ALERT]
"threadDeathWatcher-3-1" Id=30 TIMED_WAITING
        at java.lang.Thread.sleep(Native Method)
        at io.netty.util.ThreadDeathWatcher$Watcher.run(ThreadDeathWatcher.java:150)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
        at java.lang.Thread.run(Unknown Source)

"Timer-1" Id=28 TIMED_WAITING on java.util.TaskQueue@6aa6c17
        at java.lang.Object.wait(Native Method)
        -  waiting on java.util.TaskQueue@6aa6c17
        at java.util.TimerThread.mainLoop(Unknown Source)
        at java.util.TimerThread.run(Unknown Source)

"Nukkit Asynchronous Task Handler #6" Id=26 WAITING on java.util.concurrent.SynchronousQueue$TransferStack@4756e5cc
        at sun.misc.Unsafe.park(Native Method)
        -  waiting on java.util.concurrent.SynchronousQueue$TransferStack@4756e5cc
        at java.util.concurrent.locks.LockSupport.park(Unknown Source)
        at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(Unknown Source)
        at java.util.concurrent.SynchronousQueue$TransferStack.transfer(Unknown Source)
        at java.util.concurrent.SynchronousQueue.take(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        ...

"Nukkit Asynchronous Task Handler #5" Id=25 WAITING on java.util.concurrent.SynchronousQueue$TransferStack@4756e5cc
        at sun.misc.Unsafe.park(Native Method)
        -  waiting on java.util.concurrent.SynchronousQueue$TransferStack@4756e5cc
        at java.util.concurrent.locks.LockSupport.park(Unknown Source)
        at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(Unknown Source)
        at java.util.concurrent.SynchronousQueue$TransferStack.transfer(Unknown Source)
        at java.util.concurrent.SynchronousQueue.take(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        ...

"Nukkit Asynchronous Task Handler #4" Id=24 WAITING on java.util.concurrent.SynchronousQueue$TransferStack@4756e5cc
        at sun.misc.Unsafe.park(Native Method)
        -  waiting on java.util.concurrent.SynchronousQueue$TransferStack@4756e5cc
        at java.util.concurrent.locks.LockSupport.park(Unknown Source)
        at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(Unknown Source)
        at java.util.concurrent.SynchronousQueue$TransferStack.transfer(Unknown Source)
        at java.util.concurrent.SynchronousQueue.take(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        ...

"Nukkit Asynchronous Task Handler #3" Id=23 WAITING on java.util.concurrent.SynchronousQueue$TransferStack@4756e5cc
        at sun.misc.Unsafe.park(Native Method)
        -  waiting on java.util.concurrent.SynchronousQueue$TransferStack@4756e5cc
        at java.util.concurrent.locks.LockSupport.park(Unknown Source)
        at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(Unknown Source)
        at java.util.concurrent.SynchronousQueue$TransferStack.transfer(Unknown Source)
        at java.util.concurrent.SynchronousQueue.take(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        ...

"Nukkit Asynchronous Task Handler #1" Id=21 WAITING on java.util.concurrent.SynchronousQueue$TransferStack@4756e5cc
        at sun.misc.Unsafe.park(Native Method)
        -  waiting on java.util.concurrent.SynchronousQueue$TransferStack@4756e5cc
        at java.util.concurrent.locks.LockSupport.park(Unknown Source)
        at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(Unknown Source)
        at java.util.concurrent.SynchronousQueue$TransferStack.transfer(Unknown Source)
        at java.util.concurrent.SynchronousQueue.take(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        ...

"Timer-0" Id=19 WAITING on java.util.TaskQueue@2e349cf2
        at java.lang.Object.wait(Native Method)
        -  waiting on java.util.TaskQueue@2e349cf2
        at java.lang.Object.wait(Unknown Source)
        at java.util.TimerThread.mainLoop(Unknown Source)
        at java.util.TimerThread.run(Unknown Source)

"nioEventLoopGroup-2-1" Id=18 RUNNABLE (in native)
        at sun.nio.ch.WindowsSelectorImpl$SubSelector.poll0(Native Method)
        at sun.nio.ch.WindowsSelectorImpl$SubSelector.poll(Unknown Source)
        at sun.nio.ch.WindowsSelectorImpl$SubSelector.access$400(Unknown Source)
        at sun.nio.ch.WindowsSelectorImpl.doSelect(Unknown Source)
        at sun.nio.ch.SelectorImpl.lockAndDoSelect(Unknown Source)
        -  locked io.netty.channel.nio.SelectedSelectionKeySet@3dbb3fb7
        -  locked java.util.Collections$UnmodifiableSet@68a426c3
        -  locked sun.nio.ch.WindowsSelectorImpl@182cc69e
        at sun.nio.ch.SelectorImpl.select(Unknown Source)
        at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:759)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:400)
        ...

"Abandoned connection cleanup thread" Id=17 TIMED_WAITING on java.lang.ref.ReferenceQueue$Lock@12f51a65
        at java.lang.Object.wait(Native Method)
        -  waiting on java.lang.ref.ReferenceQueue$Lock@12f51a65
        at java.lang.ref.ReferenceQueue.remove(Unknown Source)
        at com.mysql.jdbc.AbandonedConnectionCleanupThread.run(AbandonedConnectionCleanupThread.java:43)

"RakNet Thread #14" Id=14 TIMED_WAITING
        at java.lang.Thread.sleep(Native Method)
        at cn.nukkit.raknet.server.SessionManager.tickProcessor(SessionManager.java:96)
        at cn.nukkit.raknet.server.SessionManager.run(SessionManager.java:70)
        at cn.nukkit.raknet.server.SessionManager.<init>(SessionManager.java:58)
        at cn.nukkit.raknet.server.RakNetServer.run(RakNetServer.java:101)

"Console" Id=11 RUNNABLE (in native)
        at org.fusesource.jansi.internal.Kernel32.ReadConsoleInputW(Native Method)
        at org.fusesource.jansi.internal.Kernel32.readConsoleInputHelper(Kernel32.java:811)
        at org.fusesource.jansi.internal.Kernel32.readConsoleKeyInput(Kernel32.java:842)
        at org.fusesource.jansi.internal.WindowsSupport.readConsoleInput(WindowsSupport.java:97)
        at jline.WindowsTerminal.readConsoleInput(WindowsTerminal.java:214)
        at jline.WindowsTerminal.access$000(WindowsTerminal.java:54)
        at jline.WindowsTerminal$1.read(WindowsTerminal.java:156)
        at jline.internal.NonBlockingInputStream.read(NonBlockingInputStream.java:166)
        -  locked jline.internal.NonBlockingInputStream@7657d90b
        ...

"NonBlockingInputStreamThread" Id=13 WAITING on jline.internal.NonBlockingInputStream@7657d90b owned by "Console" Id=11
        at java.lang.Object.wait(Native Method)
        -  waiting on jline.internal.NonBlockingInputStream@7657d90b
        at jline.internal.NonBlockingInputStream.run(NonBlockingInputStream.java:275)
        at java.lang.Thread.run(Unknown Source)

"Thread-0" Id=10 TIMED_WAITING
        at java.lang.Thread.sleep(Native Method)
        at cn.nukkit.utils.MainLogger.flushBuffer(MainLogger.java:224)
        at cn.nukkit.utils.MainLogger.run(MainLogger.java:213)

"Attach Listener" Id=5 RUNNABLE

"Signal Dispatcher" Id=4 RUNNABLE

"Finalizer" Id=3 WAITING on java.lang.ref.ReferenceQueue$Lock@3f0c6b3c
        at java.lang.Object.wait(Native Method)
        -  waiting on java.lang.ref.ReferenceQueue$Lock@3f0c6b3c
        at java.lang.ref.ReferenceQueue.remove(Unknown Source)
        at java.lang.ref.ReferenceQueue.remove(Unknown Source)
        at java.lang.ref.Finalizer$FinalizerThread.run(Unknown Source)

"Reference Handler" Id=2 WAITING on java.lang.ref.Reference$Lock@416a4275
        at java.lang.Object.wait(Native Method)
        -  waiting on java.lang.ref.Reference$Lock@416a4275
        at java.lang.Object.wait(Unknown Source)
        at java.lang.ref.Reference.tryHandlePending(Unknown Source)
        at java.lang.ref.Reference$ReferenceHandler.run(Unknown Source)

"main" Id=1 RUNNABLE
        at sun.management.ThreadImpl.dumpThreads0(Native Method)
        at sun.management.ThreadImpl.dumpAllThreads(Unknown Source)
        at cn.nukkit.utils.Utils.getAllThreadDumps(Utils.java:111)
        at cn.nukkit.Server.tickProcessor(Server.java:814)
        at cn.nukkit.Server.start(Server.java:778)
        at cn.nukkit.Server.<init>(Server.java:469)
        at cn.nukkit.Nukkit.main(Nukkit.java:68)

**Comment by Synkstar** [comment]
Same is happening for me
